id: P868C6E3D
initial_creation_type: ocr
source_metadata:
  volumes:
    3882cfaa8c28444dac5aabf6f6ecc9b3:
      base_file: v088.txt
      image_group_id: I1PD95933
      title: ལས་བརྒྱ་རྩ་གཅིག་པ།
      total_pages: 1560
      volume_number: 88
